# Generated by Django 4.2.3 on 2023-07-14 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_customuser_wallet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='wallet',
        ),
    ]
